version: '3.8'

services:
  microservicio6:
    image: microservicio6:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql6

  mysql6:
    image: mysql:8.0
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssword!
      MYSQL_DATABASE: my-app